language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t deepakm1691/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true deepakm1691/react-test npm test

after_success:
  - docker build -t deepakm1691/multi-client ./client
  - docker build -t deepakm1691/multi-server ./server
  - docker build -t deepakm1691/multi-nginx ./nginx
  - docker build -t deepakm1691/multi-worker ./worker
  # Log into Docker CLI
#   - echo $DOCKER_PASSWORD
#   - echo $DOCKER_ID
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push it innto the dockerhub
  - docker push deepakm1691/multi-client
  - docker push deepakm1691/multi-server
  - docker push deepakm1691/multi-nginx
  - docker push deepakm1691/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-393637201617"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
